### ISSUE TITLE
No 'ipaddr' dependency

### ISSUE THREAD

**Issue by Cybertinus** [lamehost/aggregate-prefixes#1]
When you install aggregate-prefixes in a new, fresh, virtualenv it will crash because it needs the module 'ipaddr', but this isn't installed as a dependency.
```
[cybertinus@laptop Documents]$ virtualenv prefix_aggregate
Using base prefix '/usr'
New python executable in /home/cybertinus/Documents/prefix_aggregate/bin/python3
Also creating executable in /home/cybertinus/Documents/prefix_aggregate/bin/python
Installing setuptools, pip, wheel...
done.
[cybertinus@laptop Documents]$ source prefix_aggregate/bin/activate
(prefix_aggregate) [cybertinus@laptop Documents]$ pip install aggregate-prefixes
Collecting aggregate-prefixes
  Downloading aggregate_prefixes-0.6.0.tar.gz (5.4 kB)
    ERROR: Command errored out with exit status 1:
     command: '/home/cybertinus/Documents/prefix_aggregate/bin/python3' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g558svrm/aggregate-prefixes/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g558svrm/aggregate-prefixes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-g558svrm/aggregate-prefixes/pip-egg-info
         cwd: /tmp/pip-install-g558svrm/aggregate-prefixes/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g558svrm/aggregate-prefixes/setup.py", line 33, in <module>
        import aggregate_prefixes as this_package
      File "/tmp/pip-install-g558svrm/aggregate-prefixes/aggregate_prefixes/__init__.py", line 20, in <module>
        from aggregate_prefixes.aggregate_prefixes import aggregate_prefixes
      File "/tmp/pip-install-g558svrm/aggregate-prefixes/aggregate_prefixes/aggregate_prefixes.py", line 35, in <module>
        import ipaddr
    ModuleNotFoundError: No module named 'ipaddr'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(prefix_aggregate) [cybertinus@laptop Documents]$ pip install ipaddr
Collecting ipaddr
  Downloading ipaddr-2.2.0.tar.gz (26 kB)
Building wheels for collected packages: ipaddr
  Building wheel for ipaddr (setup.py) ... done
  Created wheel for ipaddr: filename=ipaddr-2.2.0-py3-none-any.whl size=18280 sha256=498b856b2129eb8a03184bd7202aa71fd8592c0c24dae930d486d9a9f1423a6c
  Stored in directory: /home/cybertinus/.cache/pip/wheels/98/cf/64/ed07a20595e7a5655414147eea8b9e6b8ffdb9246fa0102561
Successfully built ipaddr
Installing collected packages: ipaddr
Successfully installed ipaddr-2.2.0
(prefix_aggregate) [cybertinus@laptop Documents]$ pip install aggregate-prefixes
Collecting aggregate-prefixes
  Using cached aggregate_prefixes-0.6.0.tar.gz (5.4 kB)
Requirement already satisfied: ipaddr==2.2.0 in ./prefix_aggregate/lib/python3.7/site-packages (from aggregate-prefixes) (2.2.0)
Building wheels for collected packages: aggregate-prefixes
  Building wheel for aggregate-prefixes (setup.py) ... done
  Created wheel for aggregate-prefixes: filename=aggregate_prefixes-0.6.0-py3-none-any.whl size=7737 sha256=0ba97dbbce555d1d8f9f31a48096702dc6f4c505fe0898e28b7d9ddeca1b3926
  Stored in directory: /home/cybertinus/.cache/pip/wheels/77/35/51/a0846bc324f68b7c88484100db4c42f413015746f72abef319
Successfully built aggregate-prefixes
Installing collected packages: aggregate-prefixes
Successfully installed aggregate-prefixes-0.6.0
```

**Comment by lamehost** [comment]
Hello,

It looks a stale file somehow got into the package. I believe i've fixed it on the testing pypi server.

`marco@lilith:~$ virtualenv -p python3 prefix_aggregate
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/marco/prefix_aggregate/bin/python3
Also creating executable in /home/marco/prefix_aggregate/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
marco@lilith:~$ source prefix_aggregate/bin/activate
(prefix_aggregate) marco@lilith:~$ python3 -m pip install --index-url https://test.pypi.org/simple/ --no-deps aggregate-prefixes
Looking in indexes: https://test.pypi.org/simple/
Collecting aggregate-prefixes
  Downloading https://test-files.pythonhosted.org/packages/ba/13/72e9a592d01bacddcf2c1f0d157934d5760d16c16c6a92335e8e2a922224/aggregate_prefixes-0.6.1b0-py3-none-any.whl (12 kB)
Installing collected packages: aggregate-prefixes
Successfully installed aggregate-prefixes-0.6.1b0
(prefix_aggregate) marco@lilith:~$ cat aggregate-prefixes/prefixes | aggregate-prefixes -
192.0.2.0/29
`

Could you please try to install aggregate-prefixes via test.pypi.org and let me know if it works for you?
`$ python3 -m pip install --index-url https://test.pypi.org/simple/ --no-deps aggregate-prefixes`

In case it does i will update a new version on pypi
